In [159]:
import numpy as np
import sklearn.decomposition

In [260]:
# arbitrary 6x3 matrix (constructed from an example at http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html with a random column concatenated)
M = np.concatenate((np.array([[1,1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]]),map(lambda x : [x], np.round(np.random.random_sample(6),1)+1)),1)
M
H = sklearn.decomposition.NMF(n_components=2).fit(M).components_
W = sklearn.decomposition.NMF(n_components=2).fit_transform(M)
print H
print
print W

[[ 3.06656817  0.47126123  0.75606029]
 [ 0.          1.00663199  1.0455626 ]]

[[ 0.32438995  0.77958337]
 [ 0.65339092  0.73084468]
 [ 0.97549315  0.63290879]
 [ 1.30867624  0.53570293]
 [ 1.62950894 -0.        ]
 [ 1.95581175  0.04756808]]


In [284]:
# a 20x4 example in which there are explicit types (that are unknown to the algorithm)
n = 20
types = np.trunc(np.random.random_sample(n)*3)
means = [[1,2,3,4],[1,5,4,1],[10,1,2,8]]
stddevs = 0.2 * np.ones([3,4])
def gen(t):
    mean = means[t]
    sd = stddevs[t]
    sz = len(mean)
    return list(np.random.randn(sz) * sd + mean)
# generate a data matrix
M = np.round(map(gen, map(int, types)),3)

# run NMF
fit = sklearn.decomposition.NMF(n_components=3).fit(M)
H = fit.components_
W = fit.transform(M)
#print H
results = list(np.concatenate((10*W,map(lambda x:[x],types)), 1))
results.sort(key = lambda row : row[3])
results = np.array(map(lambda row : list(np.round(row,3)), results))
print results
#print map(lambda row : np.argmax(np.round(list(row[0:3]),3)), results)
# predicted clusters
print map(lambda row : np.argmax(np.round(list(row[0:3]),3)), W)
# true clusters
print map(int, types)

# use fit from above to classify a new point
fit.transform([[1,2,4,5]])

[[  2.337   6.367  16.474   0.   ]
 [  1.497   6.169  16.684   0.   ]
 [  1.404   6.821  18.967   0.   ]
 [  1.391   6.938  19.562   0.   ]
 [  1.844   6.254  18.157   0.   ]
 [  1.592   6.546  19.287   0.   ]
 [  1.307   7.324  19.336   0.   ]
 [  1.532  16.159   2.447   1.   ]
 [  1.837  16.314   2.911   1.   ]
 [  2.187  16.133   1.396   1.   ]
 [  2.175  16.651   0.291   1.   ]
 [  1.86   16.213   2.054   1.   ]
 [  2.422  17.043   0.359   1.   ]
 [ 20.18    0.806   2.447   2.   ]
 [ 21.152   0.7     0.656   2.   ]
 [ 21.048   0.      2.425   2.   ]
 [ 20.971   0.644   0.8     2.   ]
 [ 21.355   1.697   0.      2.   ]
 [ 20.577   0.313   1.801   2.   ]
 [ 20.561   0.786   1.862   2.   ]]
[0, 0, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 1, 2, 1, 1, 0, 2, 2]
[2, 2, 0, 0, 2, 2, 1, 2, 0, 0, 2, 1, 1, 1, 0, 1, 1, 2, 0, 0]


array([[ 0.19196094,  0.75860678,  2.37969049]])

In [328]:
def reformat(s):
    new_s = s.lower()
    for c in '?.!/;:':
        new_s = new_s.replace(c,'')
    return new_s

def word_dict(doc):
    words = doc.split()
    words = [reformat(w) for w in words]
    word_dict = dict()
    for w in words:
        if w in word_dict:
            word_dict[w] += 1
        else:
            word_dict[w] = 1
    return word_dict

def word_mat(docs):
    word_dicts = map(word_dict, docs)
    big_dict = dict()
    

word_dict('The quick brown fox jumped over the lazy dog')

{'brown': 1,
 'dog': 1,
 'fox': 1,
 'jumped': 1,
 'lazy': 1,
 'over': 1,
 'quick': 1,
 'the': 2}